"""
ReportingService — Automated Profit Report Generator.

Aggregates operational data from telefix.db and delivers structured
reports via Telegram at three scheduled times per day:
  09:00 → Morning briefing (last 9 hours)
  14:00 → Afternoon pulse   (last 5 hours)
  21:00 → Evening profit report (last 24 hours, full stats)

Report contents
---------------
  📊 NEXUS REPORT — EVENING
  ─────────────────────────────
  📅 Date: 2026-03-19  |  Period: Last 24 hours

  💰 REVENUE METRICS
  • New users scraped (24h): 87
  • Total pipeline users:    223
  • Active target groups:    35
  • Estimated ROI:           +64%

  📈 TRADING PERFORMANCE (Paper Mode)
  • Virtual PnL:     +$4.20
  • Win Rate:        67%  (8W / 4L)
  • Auto-Restarts:   2

  🏆 PEAK OPPORTUNITY
  • Max arbitrage gap identified: 8.3%
  • Timestamp: 14:22 UTC

  🤖 SESSION HEALTH
  • Active sessions:  50  ✅
  • Frozen sessions:  44  ⚠️
  • Health ratio:     53%

  ⚡ NODE STATUS
  • Master:  Online ✅
  • Workers: 2 active

  🔗 Dashboard: http://localhost:8001/nexus-os
  ─────────────────────────────
  Generated by Nexus Orchestrator

Report Schedule
---------------
Three times per day — configured via MultiReportingService:
  report_times = [(9, 0, "morning"), (14, 0, "afternoon"), (21, 0, "evening")]

RGB Signal
----------
When a report is being sent, the master writes "nexus:report:sending" to
Redis with a 10-second TTL.  The dashboard polls this key and flashes the
Master PC RGB Neon Blue for the duration.
"""

from __future__ import annotations

import asyncio
import glob
import json
import os
import time
from datetime import datetime, timezone
from typing import Any

import aiosqlite
import structlog

from nexus.services.trading_bot import TRADING_TICKS_REDIS_KEY

log = structlog.get_logger(__name__)

# ── Paths ──────────────────────────────────────────────────────────────────────

_PROJECT_ROOT = r"C:\Users\Yarin\Desktop\Mangement Ahu"
DB_PATH       = os.path.join(_PROJECT_ROOT, "data", "telefix.db")
SESSIONS_DIR  = os.path.join(_PROJECT_ROOT, "sessions")

# ── Redis keys ─────────────────────────────────────────────────────────────────

REPORT_SENDING_KEY  = "nexus:report:sending"
REPORT_SENDING_TTL  = 10       # seconds — dashboard flashes blue for this long
LAST_REPORT_KEY     = "nexus:report:last"
LAST_REPORT_TTL     = 86400 * 7  # keep last report for 7 days

# Keys written by prediction.py and supervisor.py
PAPER_STATS_KEY      = "nexus:stats:paper"
SUPERVISOR_STATS_KEY = "nexus:supervisor:restarts"
ARBITRAGE_TS_KEY     = TRADING_TICKS_REDIS_KEY
HEARTBEAT_PREFIX     = "nexus:heartbeat:"

# Report period names for the three daily slots
_PERIOD_NAMES: dict[int, str] = {9: "MORNING", 14: "AFTERNOON", 21: "EVENING"}


# ── Redis trading / infra stats ────────────────────────────────────────────────

async def _collect_trading_stats(redis: Any) -> dict[str, Any]:
    """
    Pull Virtual PnL, Win Rate, auto-restart count, and peak arbitrage gap
    from Redis.  All values degrade gracefully to safe defaults if the key
    doesn't exist yet.
    """
    defaults: dict[str, Any] = {
        "virtual_pnl":    0.0,
        "win_rate":       0.0,
        "wins":           0,
        "losses":         0,
        "total_trades":   0,
        "auto_restarts":  0,
        "peak_arb_pct":   0.0,
        "peak_arb_ts":    None,
        "master_online":  False,
        "worker_count":   0,
    }

    if redis is None:
        return defaults

    try:
        # ── Paper trading stats (written by prediction.py _recompute_paper_stats) ──
        raw_paper = await redis.get(PAPER_STATS_KEY)
        if raw_paper:
            paper = json.loads(raw_paper)
            total = paper.get("total_trades", 0)
            wins  = paper.get("wins", 0)
            defaults["virtual_pnl"]  = round(paper.get("virtual_pnl", 0.0), 2)
            defaults["wins"]         = wins
            defaults["losses"]       = paper.get("losses", 0)
            defaults["total_trades"] = total
            defaults["win_rate"]     = round(wins / total * 100, 1) if total > 0 else 0.0

        # ── Supervisor restart count (written by supervisor.py) ────────────────
        raw_sup = await redis.get(SUPERVISOR_STATS_KEY)
        if raw_sup:
            sup = json.loads(raw_sup)
            defaults["auto_restarts"] = sup.get("total_restarts", 0)

        # ── Peak arbitrage gap (scan last 30 time-series points) ───────────────
        raw_ts = await redis.lrange(ARBITRAGE_TS_KEY, 0, -1)
        peak_gap   = 0.0
        peak_ts    = None
        for raw_pt in raw_ts:
            try:
                pt = json.loads(raw_pt)
                b  = pt.get("binance_price")
                p  = pt.get("poly_price_raw")
                if p is None:
                    p = pt.get("poly_price")
                if b and p is not None and b > 0 and 0 < float(p) < 1:
                    # Represent gap as % of ceiling (0.52) minus raw Yes price
                    gap = max(0.52 - float(p), 0.0) * 100
                    if gap > peak_gap:
                        peak_gap = gap
                        peak_ts  = pt.get("timestamp")
            except Exception:
                pass
        defaults["peak_arb_pct"] = round(peak_gap, 2)
        defaults["peak_arb_ts"]  = peak_ts

        # ── Node status (heartbeat keys) ────────────────────────────────────────
        pattern = f"{HEARTBEAT_PREFIX}*".encode()
        cursor  = 0
        master_online = False
        worker_count  = 0
        while True:
            cursor, keys = await redis.scan(cursor=cursor, match=pattern, count=100)
            for key in keys:
                raw_hb = await redis.get(key)
                if raw_hb:
                    try:
                        hb = json.loads(raw_hb)
                        if hb.get("role") == "master":
                            master_online = True
                        elif hb.get("role") == "worker":
                            worker_count += 1
                    except Exception:
                        pass
            if cursor == 0:
                break
        defaults["master_online"] = master_online
        defaults["worker_count"]  = worker_count

    except Exception as exc:
        log.warning("trading_stats_collection_error", error=str(exc))

    return defaults


# ── Data collection ────────────────────────────────────────────────────────────

async def _collect_report_data(window_hours: int = 24) -> dict[str, Any]:
    """
    Collect all data needed for the profit report.

    Parameters
    ----------
    window_hours : int
        Time window for "new" metrics (default 24 hours).

    Returns a dict with all report fields.  Safe to call even if the DB
    is unavailable — returns zero values with db_available=False.
    """
    now_ts    = time.time()
    cutoff_ts = now_ts - (window_hours * 3600)
    cutoff_dt = datetime.fromtimestamp(cutoff_ts, tz=timezone.utc)

    # Session file counts (fast, no DB needed)
    active_sessions  = len(glob.glob(os.path.join(SESSIONS_DIR, "adders",   "*.json")))
    frozen_sessions  = len(glob.glob(os.path.join(SESSIONS_DIR, "frozen",   "*.json")))
    manager_sessions = len(glob.glob(os.path.join(SESSIONS_DIR, "managers", "*.json")))
    total_sessions   = active_sessions + frozen_sessions
    health_ratio     = (active_sessions / total_sessions * 100) if total_sessions > 0 else 0

    if not os.path.exists(DB_PATH):
        return {
            "db_available":        False,
            "window_hours":        window_hours,
            "new_scraped_users":   0,
            "total_scraped_users": 0,
            "total_pipeline":      0,
            "target_groups":       0,
            "source_groups":       0,
            "estimated_roi":       0,
            "active_sessions":     active_sessions,
            "frozen_sessions":     frozen_sessions,
            "manager_sessions":    manager_sessions,
            "health_ratio":        round(health_ratio, 1),
            "last_scraper_run":    None,
            "last_adder_run":      None,
            "forecast_history":    [],
            "generated_at":        datetime.now(timezone.utc).isoformat(),
        }

    try:
        uri = f"file:{DB_PATH.replace(chr(92), '/')}?mode=ro"
        async with aiosqlite.connect(uri, uri=True, timeout=5) as db:
            db.row_factory = aiosqlite.Row
            await db.execute("PRAGMA busy_timeout = 5000")

            # New scraped users within the window
            async with db.execute(
                "SELECT COUNT(*) AS n FROM scraped_users WHERE added_at >= ?",
                (cutoff_dt.strftime("%Y-%m-%d %H:%M:%S"),),
            ) as c:
                row = await c.fetchone()
                new_scraped = row["n"] if row else 0

            # Total distinct scraped users
            async with db.execute(
                "SELECT COUNT(DISTINCT user_id) AS n FROM scraped_users"
            ) as c:
                row = await c.fetchone()
                total_scraped = row["n"] if row else 0

            # Pipeline users
            async with db.execute("SELECT COUNT(*) AS n FROM users") as c:
                row = await c.fetchone()
                total_pipeline = row["n"] if row else 0

            # Target/source groups
            async with db.execute(
                "SELECT COUNT(*) AS n FROM targets WHERE role='target'"
            ) as c:
                row = await c.fetchone()
                target_groups = row["n"] if row else 0

            async with db.execute(
                "SELECT COUNT(*) AS n FROM targets WHERE role='source'"
            ) as c:
                row = await c.fetchone()
                source_groups = row["n"] if row else 0

            # Last run timestamps
            async with db.execute(
                "SELECT key, value FROM metrics WHERE key IN "
                "('last_run:scraper','last_run:adder')"
            ) as c:
                metrics = {r["key"]: float(r["value"] or 0) for r in await c.fetchall()}

            last_scraper = metrics.get("last_run:scraper")
            last_adder   = metrics.get("last_run:adder")

            def _fmt(ts: float | None) -> str | None:
                if not ts:
                    return None
                return datetime.fromtimestamp(ts, tz=timezone.utc).strftime(
                    "%Y-%m-%d %H:%M UTC"
                )

            # Forecast history
            async with db.execute(
                "SELECT value FROM settings WHERE key='forecast:history'"
            ) as c:
                row = await c.fetchone()
                forecast_raw = row["value"] if row else ""
            forecast_history = (
                [d.strip() for d in forecast_raw.split(",") if d.strip()]
                if forecast_raw
                else []
            )

        # Estimated ROI (simplified model)
        cost_per_k    = 0.5
        price_per_grp = 10.0
        k_per_grp     = 1.0
        total_cost    = max(target_groups, 1) * k_per_grp * cost_per_k
        potential_rev = max(target_groups, 1) * price_per_grp
        realistic_net = potential_rev * 0.8 - total_cost
        estimated_roi = int(realistic_net / total_cost * 100) if total_cost > 0 else 0

        return {
            "db_available":        True,
            "window_hours":        window_hours,
            "new_scraped_users":   new_scraped,
            "total_scraped_users": total_scraped,
            "total_pipeline":      total_pipeline,
            "target_groups":       target_groups,
            "source_groups":       source_groups,
            "estimated_roi":       estimated_roi,
            "active_sessions":     active_sessions,
            "frozen_sessions":     frozen_sessions,
            "manager_sessions":    manager_sessions,
            "health_ratio":        round(health_ratio, 1),
            "last_scraper_run":    _fmt(last_scraper),
            "last_adder_run":      _fmt(last_adder),
            "forecast_history":    forecast_history,
            "generated_at":        datetime.now(timezone.utc).isoformat(),
        }

    except Exception as exc:
        log.error("reporting_data_error", error=str(exc))
        return {
            "db_available":        False,
            "window_hours":        window_hours,
            "new_scraped_users":   0,
            "total_scraped_users": 0,
            "total_pipeline":      0,
            "target_groups":       0,
            "source_groups":       0,
            "estimated_roi":       0,
            "active_sessions":     active_sessions,
            "frozen_sessions":     frozen_sessions,
            "manager_sessions":    manager_sessions,
            "health_ratio":        round(health_ratio, 1),
            "last_scraper_run":    None,
            "last_adder_run":      None,
            "forecast_history":    [],
            "generated_at":        datetime.now(timezone.utc).isoformat(),
        }


# ── Report formatting ──────────────────────────────────────────────────────────

def _format_report(data: dict[str, Any], period_name: str = "DAILY") -> str:
    """
    Format the report data as a Telegram plain-text message.

    Includes: Revenue, Trading Performance (Virtual PnL + Win Rate),
    Peak Opportunity (max arbitrage gap), Session Health, Node Status.
    """
    now     = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    time_str = datetime.now(timezone.utc).strftime("%H:%M UTC")
    divider = "─" * 32
    window  = data["window_hours"]
    period  = f"Last {window}h"

    health_icon = "✅" if data["health_ratio"] >= 60 else "⚠️"
    roi_sign    = "+" if data["estimated_roi"] >= 0 else ""

    # Trading section
    td = data.get("trading", {})
    pnl        = td.get("virtual_pnl", 0.0)
    win_rate   = td.get("win_rate", 0.0)
    wins       = td.get("wins", 0)
    losses     = td.get("losses", 0)
    restarts   = td.get("auto_restarts", 0)
    peak_pct   = td.get("peak_arb_pct", 0.0)
    peak_ts    = td.get("peak_arb_ts")
    master_ok  = td.get("master_online", False)
    workers    = td.get("worker_count", 0)

    pnl_sign  = "+" if pnl >= 0 else ""
    peak_time = ""
    if peak_ts:
        try:
            peak_time = f" @ {datetime.fromisoformat(peak_ts).strftime('%H:%M UTC')}"
        except Exception:
            pass

    lines = [
        f"📊 *NEXUS {period_name} REPORT*",
        divider,
        f"📅 {now}  |  {time_str}  |  {period}",
        "",
        "💰 *REVENUE METRICS*",
        f"• New users scraped:  {data['new_scraped_users']}",
        f"• Total pipeline:     {data['total_pipeline']}",
        f"• Target groups:      {data['target_groups']}",
        f"• Estimated ROI:      {roi_sign}{data['estimated_roi']}%",
        "",
        "📈 *TRADING PERFORMANCE (Paper Mode)*",
        f"• Virtual PnL:        {pnl_sign}${pnl:.2f}",
        f"• Win Rate:           {win_rate:.1f}%  ({wins}W / {losses}L)",
        f"• Auto-Restarts:      {restarts}",
        "",
        "🏆 *PEAK OPPORTUNITY*",
        (
            f"• Max arbitrage gap:  {peak_pct:.1f}%{peak_time}"
            if peak_pct > 0
            else "• No arbitrage gap detected yet"
        ),
        "",
        "🤖 *SESSION HEALTH*",
        f"• Active sessions:    {data['active_sessions']}  {health_icon}",
        (
            f"• Frozen sessions:    {data['frozen_sessions']}  ⚠️"
            if data["frozen_sessions"] > 0
            else f"• Frozen sessions:    {data['frozen_sessions']}  ✅"
        ),
        f"• Manager sessions:   {data['manager_sessions']}  ✅",
        f"• Health ratio:       {data['health_ratio']:.0f}%",
        "",
        "⚡ *NODE STATUS*",
        f"• Master:             {'Online ✅' if master_ok else 'Offline ❌'}",
        f"• Workers active:     {workers}",
    ]

    if data.get("last_scraper_run"):
        lines.append(f"• Last scrape:        {data['last_scraper_run']}")
    if data.get("last_adder_run"):
        lines.append(f"• Last adder:         {data['last_adder_run']}")

    lines += [
        "",
        divider,
        "🔗 http://localhost:8001/nexus-os",
        divider,
        "Generated by Nexus Orchestrator",
    ]

    return "\n".join(lines)


# ── ReportingService ───────────────────────────────────────────────────────────

class ReportingService:
    """
    Single-slot daily report service.

    Fires once per day at (report_hour, report_minute) local time.
    Use MultiReportingService for the default three-slot schedule
    (09:00 / 14:00 / 21:00).

    Usage
    -----
        svc = ReportingService(notifier=notifier, redis=redis)
        asyncio.create_task(svc.run_loop())   # fires daily at report_hour

    Or trigger manually:
        await svc.send_report()
    """

    def __init__(
        self,
        notifier: Any,   # nexus.shared.notifications.service.NotificationService
        redis: Any,      # redis.asyncio.Redis
        report_hour: int = 21,
        report_minute: int = 0,
        window_hours: int = 24,
        period_name: str = "DAILY",
    ) -> None:
        self._notifier      = notifier
        self._redis         = redis
        self._report_hour   = report_hour
        self._report_minute = report_minute
        self._window_hours  = window_hours
        self._period_name   = period_name
        self._running       = False

    async def run_loop(self) -> None:
        """
        Background loop — fires the report at (report_hour, report_minute)
        local time.  Wakes up every 60 seconds to check.
        """
        self._running = True
        log.info(
            "reporting_service_started",
            at=f"{self._report_hour:02d}:{self._report_minute:02d}",
            period=self._period_name,
        )
        last_fired_date = ""

        while self._running:
            await asyncio.sleep(60)
            now   = datetime.now()
            today = now.strftime("%Y-%m-%d")

            if (
                now.hour   == self._report_hour
                and now.minute == self._report_minute
                and last_fired_date != today
            ):
                last_fired_date = today
                log.info("reporting_service_firing", date=today, period=self._period_name)
                try:
                    await self.send_report()
                except Exception as exc:
                    log.error("reporting_service_error", error=str(exc))

    def stop(self) -> None:
        self._running = False

    async def send_report(self, window_hours: int | None = None) -> dict[str, Any]:
        """
        Generate and deliver the profit report immediately.

        Steps
        -----
        1. Set nexus:report:sending in Redis (triggers Neon Blue RGB flash).
        2. Collect data from telefix.db and Redis trading stats.
        3. Format the report text with all performance metrics.
        4. Fan out to all notification providers (Telegram).
        5. Store the report in nexus:report:last for the API to serve.
        6. Clear the sending flag.

        Returns the raw report data dict.
        """
        wh = window_hours or self._window_hours

        # ── 1. Set RGB flash signal ────────────────────────────────────────────
        await self._set_sending(True)

        try:
            # ── 2. Collect data ────────────────────────────────────────────────
            data, trading = await asyncio.gather(
                _collect_report_data(window_hours=wh),
                _collect_trading_stats(self._redis),
            )
            data["trading"] = trading

            log.info(
                "report_data_collected",
                period=self._period_name,
                new_users=data["new_scraped_users"],
                roi=data["estimated_roi"],
                sessions=data["active_sessions"],
                virtual_pnl=trading.get("virtual_pnl"),
                win_rate=trading.get("win_rate"),
            )

            # ── 3. Format ──────────────────────────────────────────────────────
            report_text = _format_report(data, period_name=self._period_name)

            # ── 4. Deliver via all providers ───────────────────────────────────
            if self._notifier:
                from nexus.shared.notifications.base import Alert, AlertLevel  # noqa: PLC0415
                alert = Alert(
                    title=f"📊 Nexus {self._period_name.title()} Report",
                    body=report_text,
                    level=AlertLevel.INFO,
                    metadata={
                        "new_users":     data["new_scraped_users"],
                        "roi":           f"{data['estimated_roi']}%",
                        "sessions":      data["active_sessions"],
                        "health":        f"{data['health_ratio']:.0f}%",
                        "virtual_pnl":   f"${trading.get('virtual_pnl', 0):.2f}",
                        "win_rate":      f"{trading.get('win_rate', 0):.1f}%",
                        "auto_restarts": trading.get("auto_restarts", 0),
                        "dashboard":     "http://localhost:8001/nexus-os",
                    },
                )
                await self._notifier.notify(alert)
                log.info("report_delivered", providers=self._notifier.provider_names)

            # ── 5. Store last report ───────────────────────────────────────────
            if self._redis:
                await self._redis.set(
                    LAST_REPORT_KEY,
                    json.dumps(data),
                    ex=LAST_REPORT_TTL,
                )

            return data

        finally:
            # ── 6. Clear RGB flash (hold for TTL then auto-expires) ────────────
            await asyncio.sleep(REPORT_SENDING_TTL)
            await self._set_sending(False)

    async def _set_sending(self, sending: bool) -> None:
        """Write/clear the report-sending flag in Redis."""
        if self._redis is None:
            return
        if sending:
            payload = json.dumps({
                "sending":    True,
                "period":     self._period_name,
                "started_at": datetime.now(timezone.utc).isoformat(),
            })
            await self._redis.set(REPORT_SENDING_KEY, payload, ex=REPORT_SENDING_TTL)
        else:
            await self._redis.delete(REPORT_SENDING_KEY)


# ── MultiReportingService ──────────────────────────────────────────────────────

class MultiReportingService:
    """
    Three-slot daily reporting service.

    Default schedule (local time):
        09:00 → Morning briefing  (last  9 hours)
        14:00 → Afternoon pulse   (last  5 hours)
        21:00 → Evening report    (last 24 hours — full stats)

    Usage
    -----
        svc = MultiReportingService(notifier=notifier, redis=redis)
        asyncio.create_task(svc.run_loop())
    """

    # (hour, minute, period_name, window_hours)
    DEFAULT_SCHEDULE = [
        (9,  0, "MORNING",   9),
        (14, 0, "AFTERNOON", 5),
        (21, 0, "EVENING",  24),
    ]

    def __init__(
        self,
        notifier: Any,
        redis: Any,
        schedule: list[tuple[int, int, str, int]] | None = None,
    ) -> None:
        self._notifier = notifier
        self._redis    = redis
        self._schedule = schedule or self.DEFAULT_SCHEDULE
        self._running  = False

        # Instantiate one ReportingService per slot
        self._services: list[ReportingService] = [
            ReportingService(
                notifier=notifier,
                redis=redis,
                report_hour=h,
                report_minute=m,
                window_hours=wh,
                period_name=name,
            )
            for h, m, name, wh in self._schedule
        ]

    async def run_loop(self) -> None:
        """Launch all per-slot loops concurrently."""
        self._running = True
        schedule_str = ", ".join(
            f"{h:02d}:{m:02d} ({n})" for h, m, n, _ in self._schedule
        )
        log.info("multi_reporting_started", schedule=schedule_str)
        await asyncio.gather(*[svc.run_loop() for svc in self._services])

    def stop(self) -> None:
        self._running = False
        for svc in self._services:
            svc.stop()

    async def send_all(self) -> list[dict[str, Any]]:
        """Manually trigger all report slots (useful for testing)."""
        results = await asyncio.gather(
            *[svc.send_report() for svc in self._services],
            return_exceptions=True,
        )
        return [r for r in results if isinstance(r, dict)]
