"""
Autonomous desktop project genesis — periodic AI-style developer loop.

Every ``NEXUS_PROJECT_GENESIS_INTERVAL_SEC`` (default 900 = 15 minutes), scans the
configured Desktop root (default: current user's Desktop, same as Explorer /
Scavenger surface), creates a new ``AI_*`` project folder, writes minimal
runnable Python stubs, logs to Redis for the dashboard, and optionally
invalidates the Explorer cache so Project Hub can pick up changes.
"""

from __future__ import annotations

import os
import random
import re
import sys
import time
from pathlib import Path

import structlog

log = structlog.get_logger(__name__)

# Redis list: newest-first via LPUSH (API reads LRANGE).
PROJECT_GENESIS_HISTORY_KEY = "nexus:project_genesis:history"
PROJECT_GENESIS_HISTORY_MAX = 80
EXPLORER_PROJECTS_KEY = "nexus:explorer:projects"

_INTERVAL_DEFAULT_SEC = 15 * 60

_NAME_PREFIXES = (
    "AI_Sub_Node",
    "AI_Scraper",
    "AI_Agent",
    "AI_MicroTool",
    "AI_SwarmWorker",
)

_AGENT_PY = '''"""Auto-generated Nexus sub-node — minimal autonomous stub."""
from __future__ import annotations


def run() -> None:
    print("[agent] idle — extend this module with goals, tools, or APIs.")


if __name__ == "__main__":
    run()
'''

_SCRAPER_PY = '''"""Auto-generated utility — stdlib HTTP sample (read-only)."""
from __future__ import annotations

import urllib.request


def fetch_head(url: str = "https://example.com", max_bytes: int = 256) -> str:
    req = urllib.request.Request(url, headers={"User-Agent": "NexusGenesis/1.0"})
    with urllib.request.urlopen(req, timeout=15) as resp:
        return resp.read(max_bytes).decode("utf-8", errors="replace")


if __name__ == "__main__":
    print(fetch_head()[:200])
'''

_README = """# Auto-generated by Nexus Project Genesis

Runnable Python stubs live in this folder. Extend or delete as needed.
"""


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[3]


def _desktop_root() -> Path:
    raw = (os.getenv("NEXUS_PROJECT_GENESIS_ROOT") or "").strip()
    if raw:
        return Path(raw).expanduser().resolve()
    from nexus.shared.paths import get_telefix_path

    return get_telefix_path().resolve()


def _redis_url() -> str:
    env_url = (os.getenv("REDIS_URL") or "").strip()
    if env_url:
        return env_url
    host = (os.getenv("MASTER_IP") or "127.0.0.1").strip() or "127.0.0.1"
    port = (os.getenv("REDIS_PORT") or "6379").strip()
    db = (os.getenv("REDIS_DB") or "0").strip()
    return f"redis://{host}:{port}/{db}"


def _interval_sec() -> int:
    raw = (os.getenv("NEXUS_PROJECT_GENESIS_INTERVAL_SEC") or "").strip()
    if not raw:
        return _INTERVAL_DEFAULT_SEC
    try:
        return max(60, int(raw))
    except ValueError:
        return _INTERVAL_DEFAULT_SEC


def _next_folder_name(desktop: Path) -> str:
    """Pick AI_Sub_Node_N / AI_Scraper_N style name not already on Desktop."""
    prefix = random.choice(_NAME_PREFIXES)
    pattern = re.compile(rf"^{re.escape(prefix)}_(\d+)$")
    highest = 0
    try:
        for p in desktop.iterdir():
            if not p.is_dir():
                continue
            m = pattern.match(p.name)
            if m:
                highest = max(highest, int(m.group(1)))
    except OSError as exc:
        log.warning("genesis_desktop_list_failed", path=str(desktop), error=str(exc))
    return f"{prefix}_{highest + 1}"


def _write_boilerplate(target: Path) -> None:
    target.mkdir(parents=True, exist_ok=True)
    (target / "README.md").write_text(_README, encoding="utf-8")
    if random.random() < 0.5:
        (target / "agent.py").write_text(_AGENT_PY, encoding="utf-8")
        main_name = "agent.py"
    else:
        (target / "scraper_stub.py").write_text(_SCRAPER_PY, encoding="utf-8")
        main_name = "scraper_stub.py"
    # Tiny runner so `python run.py` always works.
    (target / "run.py").write_text(
        f'''"""Launch the generated entry ({main_name})."""
import runpy
from pathlib import Path

runpy.run_path(str(Path(__file__).resolve().parent / "{main_name}"), run_name="__main__")
''',
        encoding="utf-8",
    )


def _push_history_line(client: object, line: str) -> None:
    try:
        client.lpush(PROJECT_GENESIS_HISTORY_KEY, line)
        client.ltrim(PROJECT_GENESIS_HISTORY_KEY, 0, PROJECT_GENESIS_HISTORY_MAX - 1)
    except Exception as exc:
        log.warning("genesis_history_redis_failed", error=str(exc))


def _invalidate_explorer_cache(client: object) -> None:
    try:
        client.delete(EXPLORER_PROJECTS_KEY)
    except Exception as exc:
        log.warning("genesis_explorer_invalidate_failed", error=str(exc))


def run_genesis_cycle() -> str | None:
    """
    Perform one genesis iteration. Returns the log line on success, else None.
    """
    desktop = _desktop_root()
    if not desktop.is_dir():
        log.warning("genesis_desktop_missing", path=str(desktop))
        return None

    name = _next_folder_name(desktop)
    target = desktop / name
    if target.exists():
        log.warning("genesis_target_exists", path=str(target))
        return None

    try:
        _write_boilerplate(target)
    except OSError as exc:
        log.error("genesis_write_failed", path=str(target), error=str(exc))
        return None

    rel = f"Desktop/{name}"
    line = f"[AUTONOMOUS] Created new AI project at {rel}"

    try:
        import redis

        r = redis.Redis.from_url(_redis_url(), decode_responses=True)
        _push_history_line(r, line)
        _invalidate_explorer_cache(r)
    except Exception as exc:
        log.warning("genesis_redis_sidecar_failed", error=str(exc))

    log.info("project_genesis_created", folder=name, path=str(target))
    return line


def run_forever() -> None:
    """
    Entry point for ``multiprocessing.Process`` from ``nexus_core``.

    Set ``NEXUS_PROJECT_GENESIS_DISABLE=1`` to no-op (process still starts but
    exits immediately).
    """
    if (os.getenv("NEXUS_PROJECT_GENESIS_DISABLE") or "").strip().lower() in (
        "1",
        "true",
        "yes",
        "on",
    ):
        log.info("project_genesis_disabled")
        return

    root = _repo_root()
    if str(root) not in sys.path:
        sys.path.insert(0, str(root))

    interval = _interval_sec()
    log.info(
        "project_genesis_worker_start",
        interval_sec=interval,
        desktop=str(_desktop_root()),
    )

    while True:
        try:
            run_genesis_cycle()
        except Exception as exc:
            log.exception("project_genesis_cycle_failed", error=str(exc))
        time.sleep(interval)


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Nexus desktop project genesis worker.")
    args, _ = parser.parse_known_args()
    run_forever()
